dailytask={}
dailytask[4011]={Dailytask_Name='Dailytask_4011_Name',Dailytask_Description='Dailytask_4011_Description',Dailytask_Types='1',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4012]={Dailytask_Name='Dailytask_4012_Name',Dailytask_Description='Dailytask_4012_Description',Dailytask_Types='1',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4013]={Dailytask_Name='Dailytask_4013_Name',Dailytask_Description='Dailytask_4013_Description',Dailytask_Types='1',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4014]={Dailytask_Name='Dailytask_4014_Name',Dailytask_Description='Dailytask_4014_Description',Dailytask_Types='1',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4015]={Dailytask_Name='Dailytask_4015_Name',Dailytask_Description='Dailytask_4015_Description',Dailytask_Types='1',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
dailytask[4021]={Dailytask_Name='Dailytask_4021_Name',Dailytask_Description='Dailytask_4021_Description',Dailytask_Types='2',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='30',}
dailytask[4022]={Dailytask_Name='Dailytask_4022_Name',Dailytask_Description='Dailytask_4022_Description',Dailytask_Types='2',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='30',}
dailytask[4023]={Dailytask_Name='Dailytask_4023_Name',Dailytask_Description='Dailytask_4023_Description',Dailytask_Types='2',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='30',}
dailytask[4024]={Dailytask_Name='Dailytask_4024_Name',Dailytask_Description='Dailytask_4024_Description',Dailytask_Types='2',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='30',}
dailytask[4025]={Dailytask_Name='Dailytask_4025_Name',Dailytask_Description='Dailytask_4025_Description',Dailytask_Types='2',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='30',}
dailytask[4031]={Dailytask_Name='Dailytask_4031_Name',Dailytask_Description='Dailytask_4031_Description',Dailytask_Types='3',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4032]={Dailytask_Name='Dailytask_4032_Name',Dailytask_Description='Dailytask_4032_Description',Dailytask_Types='3',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4033]={Dailytask_Name='Dailytask_4033_Name',Dailytask_Description='Dailytask_4033_Description',Dailytask_Types='3',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4034]={Dailytask_Name='Dailytask_4034_Name',Dailytask_Description='Dailytask_4034_Description',Dailytask_Types='3',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4035]={Dailytask_Name='Dailytask_4035_Name',Dailytask_Description='Dailytask_4035_Description',Dailytask_Types='3',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
dailytask[4041]={Dailytask_Name='Dailytask_4041_Name',Dailytask_Description='Dailytask_4041_Description',Dailytask_Types='4',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4042]={Dailytask_Name='Dailytask_4042_Name',Dailytask_Description='Dailytask_4042_Description',Dailytask_Types='4',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4043]={Dailytask_Name='Dailytask_4043_Name',Dailytask_Description='Dailytask_4043_Description',Dailytask_Types='4',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4044]={Dailytask_Name='Dailytask_4044_Name',Dailytask_Description='Dailytask_4044_Description',Dailytask_Types='4',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4045]={Dailytask_Name='Dailytask_4045_Name',Dailytask_Description='Dailytask_4045_Description',Dailytask_Types='4',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
dailytask[4051]={Dailytask_Name='Dailytask_4051_Name',Dailytask_Description='Dailytask_4051_Description',Dailytask_Types='5',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4052]={Dailytask_Name='Dailytask_4052_Name',Dailytask_Description='Dailytask_4052_Description',Dailytask_Types='5',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4053]={Dailytask_Name='Dailytask_4053_Name',Dailytask_Description='Dailytask_4053_Description',Dailytask_Types='5',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4054]={Dailytask_Name='Dailytask_4054_Name',Dailytask_Description='Dailytask_4054_Description',Dailytask_Types='5',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4055]={Dailytask_Name='Dailytask_4055_Name',Dailytask_Description='Dailytask_4055_Description',Dailytask_Types='5',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
dailytask[4061]={Dailytask_Name='Dailytask_4061_Name',Dailytask_Description='Dailytask_4061_Description',Dailytask_Types='6',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4062]={Dailytask_Name='Dailytask_4062_Name',Dailytask_Description='Dailytask_4062_Description',Dailytask_Types='6',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4063]={Dailytask_Name='Dailytask_4063_Name',Dailytask_Description='Dailytask_4063_Description',Dailytask_Types='6',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4064]={Dailytask_Name='Dailytask_4064_Name',Dailytask_Description='Dailytask_4064_Description',Dailytask_Types='6',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4065]={Dailytask_Name='Dailytask_4065_Name',Dailytask_Description='Dailytask_4065_Description',Dailytask_Types='6',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
dailytask[4071]={Dailytask_Name='Dailytask_4071_Name',Dailytask_Description='Dailytask_4071_Description',Dailytask_Types='7',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='50',}
dailytask[4072]={Dailytask_Name='Dailytask_4072_Name',Dailytask_Description='Dailytask_4072_Description',Dailytask_Types='7',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='50',}
dailytask[4073]={Dailytask_Name='Dailytask_4073_Name',Dailytask_Description='Dailytask_4073_Description',Dailytask_Types='7',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='50',}
dailytask[4074]={Dailytask_Name='Dailytask_4074_Name',Dailytask_Description='Dailytask_4074_Description',Dailytask_Types='7',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='50',}
dailytask[4075]={Dailytask_Name='Dailytask_4075_Name',Dailytask_Description='Dailytask_4075_Description',Dailytask_Types='7',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='50',}
dailytask[4081]={Dailytask_Name='Dailytask_4081_Name',Dailytask_Description='Dailytask_4081_Description',Dailytask_Types='8',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4082]={Dailytask_Name='Dailytask_4082_Name',Dailytask_Description='Dailytask_4082_Description',Dailytask_Types='8',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4083]={Dailytask_Name='Dailytask_4083_Name',Dailytask_Description='Dailytask_4083_Description',Dailytask_Types='8',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4084]={Dailytask_Name='Dailytask_4084_Name',Dailytask_Description='Dailytask_4084_Description',Dailytask_Types='8',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4085]={Dailytask_Name='Dailytask_4085_Name',Dailytask_Description='Dailytask_4085_Description',Dailytask_Types='8',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
dailytask[4091]={Dailytask_Name='Dailytask_4091_Name',Dailytask_Description='Dailytask_4091_Description',Dailytask_Types='9',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4092]={Dailytask_Name='Dailytask_4092_Name',Dailytask_Description='Dailytask_4092_Description',Dailytask_Types='9',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4093]={Dailytask_Name='Dailytask_4093_Name',Dailytask_Description='Dailytask_4093_Description',Dailytask_Types='9',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4094]={Dailytask_Name='Dailytask_4094_Name',Dailytask_Description='Dailytask_4094_Description',Dailytask_Types='9',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4095]={Dailytask_Name='Dailytask_4095_Name',Dailytask_Description='Dailytask_4095_Description',Dailytask_Types='9',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
dailytask[4101]={Dailytask_Name='Dailytask_4101_Name',Dailytask_Description='Dailytask_4101_Description',Dailytask_Types='10',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4102]={Dailytask_Name='Dailytask_4102_Name',Dailytask_Description='Dailytask_4102_Description',Dailytask_Types='10',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4103]={Dailytask_Name='Dailytask_4103_Name',Dailytask_Description='Dailytask_4103_Description',Dailytask_Types='10',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4104]={Dailytask_Name='Dailytask_4104_Name',Dailytask_Description='Dailytask_4104_Description',Dailytask_Types='10',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4105]={Dailytask_Name='Dailytask_4105_Name',Dailytask_Description='Dailytask_4105_Description',Dailytask_Types='10',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
dailytask[4111]={Dailytask_Name='Dailytask_4111_Name',Dailytask_Description='Dailytask_4111_Description',Dailytask_Types='11',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4112]={Dailytask_Name='Dailytask_4112_Name',Dailytask_Description='Dailytask_4112_Description',Dailytask_Types='11',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4113]={Dailytask_Name='Dailytask_4113_Name',Dailytask_Description='Dailytask_4113_Description',Dailytask_Types='11',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4114]={Dailytask_Name='Dailytask_4114_Name',Dailytask_Description='Dailytask_4114_Description',Dailytask_Types='11',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4115]={Dailytask_Name='Dailytask_4115_Name',Dailytask_Description='Dailytask_4115_Description',Dailytask_Types='11',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
dailytask[4121]={Dailytask_Name='Dailytask_4121_Name',Dailytask_Description='Dailytask_4121_Description',Dailytask_Types='12',Dailytask_Frquency='1',Star_Number='1',Dailytask_Level='1',}
dailytask[4122]={Dailytask_Name='Dailytask_4122_Name',Dailytask_Description='Dailytask_4122_Description',Dailytask_Types='12',Dailytask_Frquency='2',Star_Number='2',Dailytask_Level='1',}
dailytask[4123]={Dailytask_Name='Dailytask_4123_Name',Dailytask_Description='Dailytask_4123_Description',Dailytask_Types='12',Dailytask_Frquency='3',Star_Number='3',Dailytask_Level='1',}
dailytask[4124]={Dailytask_Name='Dailytask_4124_Name',Dailytask_Description='Dailytask_4124_Description',Dailytask_Types='12',Dailytask_Frquency='4',Star_Number='4',Dailytask_Level='1',}
dailytask[4125]={Dailytask_Name='Dailytask_4125_Name',Dailytask_Description='Dailytask_4125_Description',Dailytask_Types='12',Dailytask_Frquency='5',Star_Number='5',Dailytask_Level='1',}
