// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "head.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace head_msg {

namespace {

const ::google::protobuf::EnumDescriptor* CSMsgName_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_head_2eproto() {
  protobuf_AddDesc_head_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "head.proto");
  GOOGLE_CHECK(file != NULL);
  CSMsgName_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_head_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_head_2eproto() {
}

void protobuf_AddDesc_head_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nhead.proto\022\010head_msg*\360{\n\tCSMsgName\022\023\n\017"
    "CSMessageHeader\020\000\022\r\n\tErrorCode\020\001\022\017\n\013CSEr"
    "rorCode\020\002\022\025\n\021CSCheckSessionReq\020\003\022\025\n\021CSCh"
    "eckSessionRsp\020\004\022\024\n\020CSGetRoleListReq\020\005\022\024\n"
    "\020CSGetRoleListRsp\020\006\022\023\n\017CSCreateRoleReq\020\007"
    "\022\023\n\017CSCreateRoleRsp\020\010\022\016\n\nCSLoginReq\020\t\022\016\n"
    "\nCSLoginRsp\020\n\022\020\n\014CSCrtRoleReq\020\013\022\020\n\014CSDel"
    "RoleReq\020\014\022\020\n\014CSCrtRoleRsp\020\r\022\023\n\017CSQuerySh"
    "ardReq\020\016\022\020\n\014CSServerBase\020\017\022\017\n\013CSShardBas"
    "e\020\020\022\023\n\017CSQueryShardRsp\020\021\022\017\n\013FlushOnline\020"
    "\022\022\017\n\013FlushServer\020\023\022\021\n\rPlayerOffline\020\024\022\r\n"
    "\tCSPingReq\020\025\022\r\n\tCSPingRsp\020\026\022\020\n\014CSTaskAcc"
    "ept\020\027\022\021\n\rCSNickNameReq\020\030\022\021\n\rCSNickNameRs"
    "p\020\031\022\032\n\026CSLoginAnnouncementReq\020\032\022\023\n\017CSFre"
    "ezeTimeRsp\020\033\022\020\n\014CSDeviceInfo\020\034\022\031\n\025CSGetR"
    "ecommendlistReq\020\035\022\031\n\025CSGetRecommendlistR"
    "sp\020\036\022\021\n\rCSLoginOutReq\020\037\022\031\n\025CSOpeningAnim"
    "ationRsp\020 \022\020\n\014CSDelUserReq\020!\022\020\n\014CSDelUse"
    "rRsp\020\"\022\021\n\rCSQueryDelReq\020#\022\021\n\rCSQueryDelR"
    "sp\020$\022\024\n\020CSRecoverUserReq\020%\022\024\n\020CSRecoverU"
    "serRsp\020&\022\021\n\rCSGetTokenReq\020\'\022\021\n\rCSGetToke"
    "nRsp\020(\022\023\n\017CSCheckTokenReq\020)\022\023\n\017CSCheckTo"
    "kenRsp\020*\022\032\n\026CSGetLastLoginSvrIDReq\020+\022\032\n\026"
    "CSGetLastLoginSvrIDRsp\020,\022\030\n\023BasicUserBat"
    "tleInfo\020\320\017\022\022\n\rUserSkillPart\020\321\017\022\022\n\rUserSk"
    "illInfo\020\322\017\022\022\n\rBasicUserInfo\020\323\017\022\022\n\rCSEnte"
    "rMapReq\020\324\017\022\022\n\rCSEnterMapRsp\020\325\017\022\022\n\rCSLeav"
    "eMapRsp\020\326\017\022\025\n\020CSGetMapUsersReq\020\327\017\022\025\n\020CSG"
    "etMapUsersRsp\020\330\017\022\026\n\021CSGetUserSkillReq\020\331\017"
    "\022\026\n\021CSGetUserSkillRsp\020\332\017\022\025\n\020CSGetUserInf"
    "oReq\020\333\017\022\025\n\020CSGetUserInfoRsp\020\334\017\022\026\n\021CSAddU"
    "serSkillReq\020\335\017\022\026\n\021CSAddUserSkillRsp\020\336\017\022\027"
    "\n\022CSUserSkillDiffReq\020\337\017\022\027\n\022CSUserSkillDi"
    "ffRsp\020\340\017\022\032\n\025CSSkillUpdateValidRsq\020\341\017\022\016\n\t"
    "CSWalkReq\020\342\017\022\016\n\tCSWalkRsp\020\343\017\022\017\n\nCSItemAt"
    "tr\020\344\017\022\020\n\013CSEquipHole\020\345\017\022\022\n\rEquipmentBase"
    "\020\346\017\022\024\n\017SpiritStoneBase\020\347\017\022\016\n\tManorBase\020\350"
    "\017\022\017\n\nCSItemInfo\020\351\017\022\022\n\rCSAllItemsReq\020\352\017\022\022"
    "\n\rCSAllItemsRsp\020\353\017\022\021\n\014CSItemAddRsp\020\354\017\022\024\n"
    "\017CSItemRemoveReq\020\355\017\022\024\n\017CSItemRemoveRsp\020\356"
    "\017\022\021\n\014CSItemUseReq\020\357\017\022\021\n\014CSItemUseRsp\020\360\017\022"
    "\022\n\rCSItemMoveReq\020\361\017\022\022\n\rCSItemMoveRsp\020\362\017\022"
    "\024\n\017CSItemUpdateRsp\020\363\017\022\023\n\016CSItemOrderReq\020"
    "\364\017\022\036\n\031CSItemMoveToRecycleBinReq\020\365\017\022\036\n\031CS"
    "ItemMoveToRecycleBinRsp\020\366\017\022\034\n\027CSRepoRecy"
    "cleBinItemReq\020\367\017\022\034\n\027CSRepoRecycleBinItem"
    "Rsp\020\370\017\022\023\n\016CSInstanceInfo\020\371\017\022\022\n\rCSInstanc"
    "eReq\020\372\017\022\022\n\rCSInstanceRsp\020\373\017\022\034\n\027CSGetUGCi"
    "tyBoxRewardReq\020\374\017\022\034\n\027CSGetUGCityBoxRewar"
    "dRsp\020\375\017\022\r\n\010CSReward\020\376\017\022\021\n\014CSLevelUpRsp\020\377"
    "\017\022\035\n\030CSBasicUserBattleInfoRsp\020\200\020\022\033\n\026CSSe"
    "archSpiritStoneReq\020\201\020\022\033\n\026CSSearchSpiritS"
    "toneRsp\020\202\020\022\034\n\027CSSpiritStoneMoveBagReq\020\203\020"
    "\022\034\n\027CSSpiritStoneMoveBagRsp\020\204\020\022\034\n\027CSSpir"
    "itStoneLevelUpReq\020\205\020\022\034\n\027CSSpiritStoneLev"
    "elUpRsp\020\206\020\022\031\n\024CSSpiritStoneToSPReq\020\207\020\022\031\n"
    "\024CSSpiritStoneToSPRsp\020\210\020\022\033\n\026CSGetExchang"
    "eSSInfoReq\020\211\020\022\023\n\016ExchangeSSInfo\020\212\020\022\033\n\026CS"
    "GetExchangeSSInfoRsp\020\213\020\022\022\n\rCSAddManorReq"
    "\020\214\020\022\022\n\rCSAddManorRsp\020\215\020\022\027\n\022CSWarmSportLv"
    "UpReq\020\216\020\022\027\n\022CSWarmSportLvUpRsp\020\217\020\022\022\n\rCSM"
    "anorOptReq\020\220\020\022\022\n\rCSManorOptRsp\020\221\020\022\021\n\014CSM"
    "onListReq\020\222\020\022\014\n\007MonInfo\020\223\020\022\021\n\014CSMonListR"
    "sp\020\224\020\022\026\n\021CSSetMonStatusReq\020\225\020\022\026\n\021CSSetMo"
    "nStatusRsp\020\226\020\022\026\n\021CSPVPQueryRoomReq\020\227\020\022\020\n"
    "\013PVPRoomBase\020\230\020\022\026\n\021CSPVPQueryRoomRsp\020\231\020\022"
    "\025\n\020CSPVPBaseInfoRsp\020\232\020\022\027\n\022CSPVPCreateRoo"
    "mReq\020\233\020\022\025\n\020CSPVPJoinRoomReq\020\234\020\022\020\n\013PVPSea"
    "tBase\020\235\020\022\025\n\020CSPVPJoinRoomRsp\020\236\020\022\025\n\020CSPVP"
    "ExitRoomReq\020\237\020\022\025\n\020CSPVPExitRoomRsp\020\240\020\022\026\n"
    "\021CSPVPCloseRoomRsp\020\241\020\022\027\n\022CSPVPChangeSeat"
    "Req\020\242\020\022\022\n\rCSPVPReadyReq\020\243\020\022\030\n\023CSPVPCance"
    "lReadyReq\020\244\020\022\024\n\017CSPVPKickoffReq\020\245\020\022\024\n\017CS"
    "PVPKickoffRsp\020\246\020\022\022\n\rCSPVPStartReq\020\247\020\022\022\n\r"
    "CSPVPStartRsp\020\250\020\022\024\n\017CSPPVEBattleReq\020\251\020\022\024"
    "\n\017CSPPVEBattleRsp\020\252\020\022\026\n\021CSPVEQueryRoomRe"
    "q\020\253\020\022\020\n\013PVERoomBase\020\254\020\022\026\n\021CSPVEQueryRoom"
    "Rsp\020\255\020\022\025\n\020CSPVEBaseInfoRsp\020\256\020\022\027\n\022CSPVECr"
    "eateRoomReq\020\257\020\022\025\n\020CSPVEJoinRoomReq\020\260\020\022\034\n"
    "\027CSPVEJoinRoomFailureRsp\020\261\020\022\020\n\013PVESeatBa"
    "se\020\262\020\022\025\n\020CSPVEJoinRoomRsp\020\263\020\022\025\n\020CSPVEExi"
    "tRoomReq\020\264\020\022\025\n\020CSPVEExitRoomRsp\020\265\020\022\026\n\021CS"
    "PVECloseRoomRsp\020\266\020\022\022\n\rCSPVEReadyReq\020\267\020\022\030"
    "\n\023CSPVECancelReadyReq\020\270\020\022\024\n\017CSPVEKickoff"
    "Req\020\271\020\022\024\n\017CSPVEKickoffRsp\020\272\020\022\022\n\rCSPVESta"
    "rtReq\020\273\020\022\022\n\rCSPVEStartRsp\020\274\020\022\016\n\tCSPVAIRe"
    "q\020\275\020\022\022\n\rCSPVAIInfoReq\020\276\020\022\022\n\rCSPVAIInfoRs"
    "q\020\277\020\022\031\n\024CSGetInstanceInfoReq\020\300\020\022\031\n\024CSGet"
    "InstanceInfoRsp\020\301\020\022\023\n\016CSPVXRewardRsp\020\302\020\022"
    "\027\n\022CSEquipInlayGemReq\020\303\020\022\027\n\022CSEquipInlay"
    "GemRsp\020\304\020\022\026\n\021CSResetGemAttrReq\020\305\020\022\026\n\021CSR"
    "esetGemAttrRsp\020\306\020\022\033\n\026CSEquipmentStrength"
    "Req\020\307\020\022\033\n\026CSEquipmentStrengthRsp\020\310\020\022\032\n\025C"
    "SEquipmentComposeReq\020\311\020\022\032\n\025CSEquipmentCo"
    "mposeRsp\020\312\020\022!\n\034CSEquipmentDecomposeQuery"
    "Req\020\313\020\022!\n\034CSEquipmentDecomposeQueryRsp\020\314"
    "\020\022\034\n\027CSEquipmentDecomposeReq\020\315\020\022\034\n\027CSEqu"
    "ipmentDecomposeRsp\020\316\020\022\022\n\rCSTaskInfoReq\020\317"
    "\020\022\r\n\010TaskInfo\020\320\020\022\022\n\rCSTaskInfoRsp\020\321\020\022\024\n\017"
    "CSTaskDoStepReq\020\322\020\022\024\n\017CSTaskDoStepRsp\020\323\020"
    "\022\021\n\014CSTaskLogReq\020\324\020\022\021\n\014CSTaskLogRsp\020\325\020\022\024"
    "\n\017CSTaskStatusReq\020\326\020\022\024\n\017CSTaskStatusRsp\020"
    "\327\020\022\022\n\rDailyTaskInfo\020\330\020\022\027\n\022CSDailyTaskInf"
    "oReq\020\331\020\022\027\n\022CSDailyTaskInfoRsp\020\332\020\022\031\n\024CSAc"
    "ceptDailyTaskReq\020\333\020\022\031\n\024CSAcceptDailyTask"
    "Rsp\020\334\020\022\031\n\024CSGiveUpDailyTaskReq\020\335\020\022\031\n\024CSG"
    "iveUpDailyTaskRsp\020\336\020\022\034\n\027CSGetDailyTaskRe"
    "wardReq\020\337\020\022\034\n\027CSGetDailyTaskRewardRsp\020\340\020"
    "\022#\n\036CSNotifyUpdateDailyTaskInfoRsp\020\341\020\022\034\n"
    "\027CSGetDailyGoalRewardReq\020\342\020\022\034\n\027CSGetDail"
    "yGoalRewardRsp\020\343\020\022\030\n\023CSGetDailyRewardReq"
    "\020\344\020\022\030\n\023CSGetDailyRewardRsp\020\345\020\022\030\n\023CSGetLo"
    "ginRewardReq\020\346\020\022\030\n\023CSGetLoginRewardRsp\020\347"
    "\020\022\036\n\031CSSelectPVAIACCURewardReq\020\350\020\022\036\n\031CSS"
    "electPVAIACCURewardRsp\020\351\020\022\027\n\022CSAttribute"
    "sSetReq\020\352\020\022\024\n\017CSAttributesReq\020\353\020\022\024\n\017CSAt"
    "tributesRsp\020\354\020\022\021\n\014CSOnceSetReq\020\355\020\022\016\n\tCSO"
    "nceReq\020\356\020\022\016\n\tCSOnceRsp\020\357\020\022\023\n\016CSTrainInfo"
    "Req\020\360\020\022\023\n\016CSTrainInfoRsp\020\361\020\022\017\n\nCSTrainRe"
    "q\020\362\020\022\017\n\nCSTrainRsp\020\363\020\022\030\n\023CSTrainDetermin"
    "eReq\020\364\020\022\030\n\023CSTrainDetermineRsp\020\365\020\022\021\n\014CSE"
    "xploreReq\020\366\020\022\021\n\014CSExploreRsp\020\367\020\022\032\n\025CSExp"
    "loreDetermineReq\020\370\020\022\032\n\025CSExploreDetermin"
    "eRsp\020\371\020\022\024\n\017CSQueryDowerReq\020\372\020\022\024\n\017CSQuery"
    "DowerRsp\020\373\020\022\023\n\016CSDowerInfoReq\020\374\020\022\023\n\016CSDo"
    "werInfoRsp\020\375\020\022\017\n\nCSDowerReq\020\376\020\022\017\n\nCSDowe"
    "rRsp\020\377\020\022\023\n\016CSABMonsterReq\020\200\021\022\023\n\016CSABMons"
    "terRsp\020\201\021\022\024\n\017CSAutoBattleReq\020\202\021\022\024\n\017CSAut"
    "oBattleRsp\020\203\021\022\022\n\rCSABRewardRsp\020\204\021\022\032\n\025CSC"
    "ancelAutoBattleReq\020\205\021\022\032\n\025CSCancelAutoBat"
    "tleRsp\020\206\021\022\033\n\026CSExchangeParameterReq\020\207\021\022\033"
    "\n\026CSExchangeParameterRsp\020\210\021\022\021\n\014ShopItemI"
    "nfo\020\211\021\022\026\n\021CSGetShopItemsReq\020\212\021\022\026\n\021CSGetS"
    "hopItemsRsp\020\213\021\022\025\n\020CSBuyShopItemReq\020\214\021\022\025\n"
    "\020CSBuyShopItemRsp\020\215\021\022\025\n\020CSGetUserItemReq"
    "\020\216\021\022\025\n\020CSGetUserItemRsp\020\217\021\022\033\n\026CSGetUserA"
    "ttributesReq\020\220\021\022\033\n\026CSGetUserAttributesRs"
    "p\020\221\021\022\035\n\030CSNotifyMoneyConfInfoRsp\020\222\021\022\035\n\030C"
    "SNotifyLevelConfInfoRsp\020\223\021\022\033\n\026CSNotifyVi"
    "pConfInfoRsp\020\224\021\022\032\n\025CSNotifyCliSysFlagRsp"
    "\020\225\021\022\020\n\013PartnerInfo\020\226\021\022\020\n\013CSNearByReq\020\227\021\022"
    "\020\n\013CSNearByRsp\020\230\021\022\025\n\020CSPartnerInfoReq\020\231\021"
    "\022\024\n\017CSAddPartnerReq\020\232\021\022\024\n\017CSDelPartnerRe"
    "q\020\233\021\022\025\n\020CSPartnerInfoRsp\020\234\021\022\024\n\017CSAddPart"
    "nerRsp\020\235\021\022\024\n\017CSDelPartnerRsp\020\236\021\022\014\n\007DndIn"
    "fo\020\237\021\022\020\n\013CSAddDndReq\020\240\021\022\021\n\014CSDndInfoReq\020"
    "\241\021\022\020\n\013CSDelDndReq\020\242\021\022\021\n\014CSDndInfoRsp\020\243\021\022"
    "\020\n\013CSAddDndRsp\020\244\021\022\020\n\013CSDelDndRsp\020\245\021\022\016\n\tC"
    "SNoteReq\020\246\021\022\016\n\tCSNoteRsp\020\247\021\022\017\n\nCSNoteSho"
    "w\020\250\021\022\016\n\tCSMailReq\020\251\021\022\017\n\nAttachItem\020\252\021\022\016\n"
    "\tCSMailRsp\020\253\021\022\r\n\010MailList\020\254\021\022\022\n\rCSMailLi"
    "stReq\020\255\021\022\022\n\rCSMailListRsp\020\256\021\022\021\n\014CSDelMai"
    "lReq\020\257\021\022\021\n\014CSDelMailRsp\020\260\021\022\023\n\016CSGetAttac"
    "hReq\020\261\021\022\023\n\016CSGetAttachRsp\020\262\021\022\021\n\014CSNewMai"
    "lRsp\020\263\021\022\026\n\021CSActivityListReq\020\264\021\022\022\n\rActiv"
    "ity_Step\020\265\021\022\022\n\rActivity_Info\020\266\021\022\026\n\021CSAct"
    "ivityListRsp\020\267\021\022\033\n\026CSGetActivityRewardRe"
    "q\020\270\021\022\033\n\026CSGetActivityRewardRsp\020\271\021\022\034\n\027CSU"
    "pdateActivityInfoRsp\020\272\021\022\031\n\024CSDelActivity"
    "InfoRsp\020\273\021\022\027\n\022CSCDEFQueryRoomReq\020\274\021\022\021\n\014C"
    "DEFRoomBase\020\275\021\022\027\n\022CSCDEFQueryRoomRsp\020\276\021\022"
    "\026\n\021CSCDEFBaseInfoRsp\020\277\021\022\030\n\023CSCDEFCreateR"
    "oomReq\020\300\021\022\026\n\021CSCDEFJoinRoomReq\020\301\021\022\035\n\030CSC"
    "DEFJoinRoomFailureRsp\020\302\021\022\021\n\014CDEFSeatBase"
    "\020\303\021\022\026\n\021CSCDEFJoinRoomRsp\020\304\021\022\026\n\021CSCDEFExi"
    "tRoomReq\020\305\021\022\027\n\022CSCDEFCloseRoomRsp\020\306\021\022\023\n\016"
    "CSCDEFReadyReq\020\307\021\022\031\n\024CSCDEFCancelReadyRe"
    "q\020\310\021\022\025\n\020CSCDEFKickoffReq\020\311\021\022\025\n\020CSCDEFKic"
    "koffRsp\020\312\021\022\023\n\016CSCDEFStartReq\020\313\021\022\035\n\030CSGet"
    "SpecActivityTimeReq\020\314\021\022\035\n\030CSGetSpecActiv"
    "ityTimeRsp\020\315\021\022\023\n\016CSCDEFStartRsp\020\316\021\022\021\n\014An"
    "nouncement\020\317\021\022\033\n\026CSLoginAnnouncementRsp\020"
    "\320\021\022\031\n\024CSAnnouncementPreReq\020\321\021\022\031\n\024CSAnnou"
    "ncementPreRsp\020\322\021\022\026\n\021CSAnnouncementReq\020\323\021"
    "\022\026\n\021CSAnnouncementRsp\020\324\021\022\027\n\022CSMaAdvertis"
    "ingRsp\020\325\021\022\014\n\007CSStyle\020\326\021\022\016\n\tCSMaStyle\020\327\021\022"
    "\035\n\030CSNotifyRewardToOtherRsp\020\330\021\022\r\n\010LyleMs"
    "g1\020\331\021\022\r\n\010LyleMsg2\020\332\021\022\r\n\010LyleMsg3\020\333\021\022\r\n\010L"
    "yleMsg4\020\334\021\022\036\n\031CSGetChipComposeStatusReq\020"
    "\335\021\022\036\n\031CSGetChipComposeStatusRsp\020\336\021\022\031\n\024CS"
    "GetActivityRankReq\020\337\021\022\031\n\024CSGetActivityRa"
    "nkRsp\020\340\021\022\027\n\022CSAskOnlineGiftReq\020\341\021\022\027\n\022CSA"
    "skOnlineGiftRsp\020\342\021\022\027\n\022CSGetOnlineGiftReq"
    "\020\343\021\022\027\n\022CSGetOnlineGiftRsp\020\344\021\022\031\n\024CSCheckT"
    "opupAwardReq\020\345\021\022\031\n\024CSCheckTopupAwardRsp\020"
    "\346\021\022\027\n\022CSGetTopupAwardReq\020\347\021\022\027\n\022CSGetTopu"
    "pAwardRsp\020\350\021\022\022\n\rCSPVP2JoinReq\020\351\021\022\022\n\rCSPV"
    "P2JoinRsp\020\352\021\022\027\n\022CSPVP2BtlCancelReq\020\353\021\022\027\n"
    "\022CSPVP2BtlCancelRsp\020\354\021\022\024\n\017CSPVP2RewardRs"
    "p\020\355\021\022\023\n\016CSQueryRankReq\020\356\021\022\023\n\016CSQueryRank"
    "Rsp\020\357\021\022\035\n\030CSQueryPlayerRankInfoReq\020\360\021\022\035\n"
    "\030CSQueryPlayerRankInfoRsp\020\361\021\022\030\n\023CSQueryR"
    "ankCountReq\020\362\021\022\030\n\023CSQueryRankCountRsp\020\363\021"
    "\022\r\n\010LyleMsg7\020\364\021\022\r\n\010LyleMsg8\020\365\021\022\024\n\017CSMail"
    "BasicInfo\020\366\021\022\017\n\nCSMailInfo\020\367\021\022\025\n\020CSGetMa"
    "ilListReq\020\370\021\022\025\n\020CSGetMailListRsp\020\371\021\022\025\n\020C"
    "SGetMailInfoReq\020\372\021\022\025\n\020CSGetMailInfoRsp\020\373"
    "\021\022\017\n\nMailStatus\020\374\021\022\027\n\022CSSetMailStatusReq"
    "\020\375\021\022\027\n\022CSSetMailStatusRsp\020\376\021\022\033\n\026CSNotify"
    "MailNumInfoRsp\020\377\021\022\021\n\014CSMarqueeRsp\020\200\022\022\023\n\016"
    "CSMagicCardReq\020\201\022\022\023\n\016CSMagicCardRsp\020\202\022\022\027"
    "\n\022CSPVPSetOpeningReq\020\203\022\022\027\n\022CSPVPSetOpeni"
    "ngRsp\020\204\022\022\027\n\022CSPVESetOpeningReq\020\205\022\022\027\n\022CSP"
    "VESetOpeningRsp\020\206\022\022\016\n\tbase_info\020\207\022\022\030\n\023pl"
    "ayer_basic_info_t\020\210\022\022\030\n\023CSInviteToBattle"
    "Req\020\211\022\022\030\n\023CSInviteToBattleRsp\020\212\022\022\030\n\023CSAn"
    "swerToBattleReq\020\213\022\022\030\n\023CSAnswerToBattleRs"
    "p\020\214\022\022\032\n\025CSLookupFriendListReq\020\215\022\022\032\n\025CSLo"
    "okupFriendListRsp\020\216\022\022\017\n\nFairyBasic\020\217\022\022\016\n"
    "\tFairyAttr\020\220\022\022\023\n\016FairyTrainAttr\020\221\022\022\016\n\tFa"
    "iryInfo\020\222\022\022\026\n\021CSGetFairyListReq\020\223\022\022\026\n\021CS"
    "GetFairyListRsp\020\224\022\022\026\n\021CSMoveFairyPosReq\020"
    "\225\022\022\026\n\021CSMoveFairyPosRsp\020\226\022\022\024\n\017CSFairyTra"
    "inReq\020\227\022\022\024\n\017CSFairyTrainRsp\020\230\022\022\035\n\030CSFair"
    "yTrainDetermineReq\020\231\022\022\035\n\030CSFairyTrainDet"
    "ermineRsp\020\232\022\022\025\n\020CSFairyAddExpReq\020\233\022\022\025\n\020C"
    "SFairyAddExpRsp\020\234\022\022\033\n\026CSFairyUpGradeLeve"
    "lReq\020\235\022\022\033\n\026CSFairyUpGradeLevelRsp\020\236\022\022\030\n\023"
    "CSFairyDecomposeReq\020\237\022\022\030\n\023CSFairyDecompo"
    "seRsp\020\240\022\022\026\n\021CSFairyRebirthReq\020\241\022\022\026\n\021CSFa"
    "iryRebirthRsp\020\242\022\022\030\n\023CSNotifyAddFairyRsp\020"
    "\243\022\022\033\n\026CSNotifyUpdateFairyRsp\020\244\022\022\030\n\023CSNot"
    "ifyDelFairyRsp\020\245\022\022\r\n\010LyleMsg9\020\246\022\022\016\n\tLyle"
    "Msg10\020\247\022\022\016\n\tLyleMsg11\020\250\022\022\016\n\tLyleMsg12\020\251\022"
    "\022\r\n\010kakao_cd\020\252\022\022\026\n\021CSQueryKakaoCdReq\020\253\022\022"
    "\026\n\021CSQueryKakaoCdRsp\020\254\022\022\023\n\016CSSendPowerRe"
    "q\020\255\022\022\022\n\rCSSendPoweRsp\020\256\022\022\030\n\023CSGetPowerRe"
    "wardReq\020\257\022\022\030\n\023CSGetPowerRewardRsp\020\260\022\022\030\n\023"
    "CSPushMsgToKakaoReq\020\261\022\022\030\n\023CSPushMsgToKak"
    "aoRsp\020\262\022\022\031\n\024CSKakaolistFriendReq\020\263\022\022\031\n\024C"
    "SKakaolistFriendRsp\020\264\022\022\030\n\023CSKakaoAddFrie"
    "ndReq\020\265\022\022\030\n\023CSKakaoAddFriendRsp\020\266\022\022\033\n\026CS"
    "KakaoAnswerFriendReq\020\267\022\022\033\n\026CSKakaoAnswer"
    "FriendRsp\020\270\022\022\030\n\023CSKakaoDelFriendReq\020\271\022\022\024"
    "\n\017CSKakaoDBAddRsp\020\272\022\022\031\n\024CSPVPLearnPrepar"
    "eReq\020\273\022\022\031\n\024CSPVPLearnPrepareRsp\020\274\022\022\022\n\rCS"
    "PVPLearnReq\020\275\022\022\022\n\rCSPVPLearnRsp\020\276\022\022\033\n\026CS"
    "PVPLearnMandatoryRsp\020\277\022\022\025\n\020CSPVPAckLearn"
    "Req\020\300\022\022\033\n\026CSPVPAckLearnRefuseRsp\020\301\022\022\031\n\024C"
    "SAutoBattleCheckReq\020\302\022\022\031\n\024CSAutoBattleCh"
    "eckRsp\020\303\022\022\027\n\022CSNearbyRednameReq\020\304\022\022\027\n\022CS"
    "NearbyRednameRsp\020\305\022\022\034\n\027CSInstanceStarRew"
    "ardReq\020\306\022\022\034\n\027CSInstanceStarRewardRsp\020\307\022\022"
    "\037\n\032CSInstanceGetStarRewardReq\020\310\022\022\037\n\032CSIn"
    "stanceGetStarRewardRsp\020\311\022\022\037\n\032CSChkInstan"
    "ceStarRewardReq\020\312\022\022\037\n\032CSChkInstanceStarR"
    "ewardRsp\020\313\022\022\022\n\rCSDelEnemyReq\020\314\022\022\022\n\rCSDel"
    "EnemyRsp\020\315\022\022\023\n\016CSEnemyInfoReq\020\316\022\022\023\n\016CSEn"
    "emyInfoRsp\020\317\022\022\030\n\023CSGetRednameTimeReq\020\320\022\022"
    "\030\n\023CSGetRednameTimeRsp\020\321\022\022\024\n\017CSSpiritDra"
    "wReq\020\322\022\022\024\n\017CSSpiritDrawRsp\020\323\022\022\026\n\021CSEquip"
    "AllBestReq\020\324\022\022\030\n\023CSCALBattleFairyReq\020\325\022\022"
    "\030\n\023CSCALBattleFairyRsp\020\326\022\022\025\n\020CSBabelFact"
    "orReq\020\327\022\022\025\n\020CSBabelFactorRsp\020\330\022\022\023\n\016CSSho"
    "ppingInfo\020\331\022\022\022\n\rCSShoppingReq\020\332\022\022\022\n\rCSSh"
    "oppingRsp\020\333\022\022\022\n\rCSEquipNotify\020\334\022\022\030\n\023CSSh"
    "owRebirthNotify\020\335\022\022\025\n\020CSNewFairyNotify\020\336"
    "\022\022\027\n\022CSGoogleGradingRsp\020\337\022\022\037\n\032CSGoogleGr"
    "adingCompleteReq\020\340\022\022\023\n\016CSKakaoAttrReq\020\341\022"
    "\022\023\n\016CSKakaoAttrRsp\020\342\022\022\022\n\rCSkakaoUrlReq\020\343"
    "\022\022\025\n\020CSGetCdRewardReq\020\344\022\022\025\n\020CSGetCdRewar"
    "dRsp\020\345\022\022\026\n\021CSEquipAllBestRsp\020\346\022\022\027\n\022CSGoo"
    "gleGradingReq\020\347\022\022\034\n\027CSGetExploreTreasure"
    "Req\020\350\022\022\034\n\027CSGetExploreTreasureRsp\020\351\022\022\030\n\023"
    "CSGetExploreInfoReq\020\352\022\022\030\n\023CSGetExploreIn"
    "foRsp\020\353\022\022\031\n\024CSGetActivityDataReq\020\354\022\022\035\n\030C"
    "SActivityCentreItemInfo\020\355\022\022\033\n\026CSShowActi"
    "vityItemInfo\020\356\022\022\031\n\024CSGetActivityDataRsp\020"
    "\357\022\022\r\n\010carmsg01\020\360\022\022\r\n\010carmsg02\020\361\022\022\r\n\010carm"
    "sg03\020\362\022\022\r\n\010carmsg04\020\363\022\022\r\n\010carmsg05\020\364\022\022\024\n"
    "\017CSTargetListReq\020\365\022\022\016\n\tStep_Rate\020\366\022\022\020\n\013T"
    "arget_Info\020\367\022\022\024\n\017CSTargetListRsp\020\370\022\022\031\n\024C"
    "SGetTargetRewardReq\020\371\022\022\031\n\024CSGetTargetRew"
    "ardRsp\020\372\022\022\032\n\025CSUpdateTargetInfoRsp\020\373\022\022\025\n"
    "\020CSDelTargetfoRsp\020\374\022\022\037\n\032CSExchangeParame"
    "terListReq\020\375\022\022\037\n\032CSExchangeParameterList"
    "Rsp\020\376\022\022\030\n\023CSTargetFinishedRsp\020\377\022\022\023\n\016CSMc"
    "ardInfoReq\020\200\023\022\016\n\tMcardInfo\020\201\023\022\023\n\016CSMcard"
    "InfoRsp\020\202\023\022\025\n\020CSMcardRewardReq\020\203\023\022\025\n\020CSM"
    "cardRewardRsp\020\204\023\022\025\n\020CSCreateGuildReq\020\205\023\022"
    "\025\n\020CSCreateGuildRsp\020\206\023\022\023\n\016CSJoinGuildReq"
    "\020\207\023\022\023\n\016CSJoinGuildRsp\020\210\023\022\023\n\016CSDropGuildR"
    "eq\020\211\023\022\023\n\016CSDropGuildRsp\020\212\023\022\023\n\016CSQuitGuil"
    "dReq\020\213\023\022\023\n\016CSQuitGuildRsp\020\214\023\022\020\n\013CSGuildI"
    "nfo\020\215\023\022\023\n\016CSListGuildReq\020\216\023\022\023\n\016CSListGui"
    "ldRsp\020\217\023\022\025\n\020CSSearchGuildReq\020\220\023\022\025\n\020CSSea"
    "rchGuildRsp\020\221\023\022\031\n\024CSListPlayerGuildReq\020\222"
    "\023\022\026\n\021CSPlayerGuildInfo\020\223\023\022\031\n\024CSListPlaye"
    "rGuildRsp\020\224\023\022\020\n\013PlayerGuild\020\225\023\022&\n!CSChan"
    "geOtherPlayerGuildStatusReq\020\226\023\022!\n\034CSChan"
    "gePlayerGuildStatusRsp\020\227\023\022\030\n\023CSSetGuildN"
    "oticeReq\020\230\023\022\030\n\023CSSetGuildNoticeRsp\020\231\023\022\032\n"
    "\025CSGetRecruitMemberReq\020\232\023\022\032\n\025CSGetRecrui"
    "tMemberRsp\020\233\023\022\017\n\nCSPVAI3Req\020\234\023\022\027\n\022CSQuer"
    "yNewDowerReq\020\235\023\022\027\n\022CSQueryNewDowerRsp\020\236\023"
    "\022\022\n\rCSNewDowerReq\020\237\023\022\022\n\rCSNewDowerRsp\020\240\023"
    "\022\030\n\023CSNewDowerOneKeyReq\020\241\023\022\030\n\023CSNewDower"
    "OneKeyRsp\020\242\023\022\017\n\nCSTitleReq\020\243\023\022\016\n\tTitleIn"
    "fo\020\244\023\022\017\n\nCSTitleRsp\020\245\023\022\024\n\017CSTitleLearnRe"
    "q\020\246\023\022\024\n\017CSTitleLearnRsp\020\247\023\022\023\n\016CSTitleWea"
    "rReq\020\250\023\022\023\n\016CSTitleWearRsp\020\251\023\022\025\n\020CSTitleU"
    "nlockRsp\020\252\023\022\033\n\026CSPGSetAcceptInviteReq\020\253\023"
    "\022\033\n\026CSPGSetAcceptInviteRsp\020\254\023\022\035\n\030CSPGCon"
    "tributeToGuildReq\020\255\023\022\035\n\030CSPGContributeTo"
    "GuildRsp\020\256\023\022\027\n\022CSCancelWaitingRsp\020\257\023\022\036\n\031"
    "CSQueryPlayerGuildInfoReq\020\260\023\022\036\n\031CSQueryP"
    "layerGuildInfoRsp\020\261\023\022&\n!CSSetPlayerGuild"
    "ApplyConditionReq\020\262\023\022&\n!CSSetPlayerGuild"
    "ApplyConditionRsp\020\263\023\022\024\n\017GuildRecordInfo\020"
    "\264\023\022\031\n\024CSGuildRecordListReq\020\265\023\022\031\n\024CSGuild"
    "RecordListRsp\020\266\023\022\026\n\021CSGoddessBlessReq\020\267\023"
    "\022\026\n\021CSGoddessBlessRsp\020\270\023\022\025\n\020ShoppingItem"
    "Info\020\271\023\022\032\n\025CSGetShoppingItemsReq\020\272\023\022\032\n\025C"
    "SGetShoppingItemsRsp\020\273\023\022\032\n\025CSExchangeIte"
    "mInfoReq\020\274\023\022\032\n\025CSExchangeItemInfoRsp\020\275\023\022"
    "\023\n\016CSGuildNoteRsp\020\276\023\022\030\n\023CSGuildRedPacket"
    "Key\020\277\023\022\031\n\024CSGuildRedPacketInfo\020\300\023\022\035\n\030CSG"
    "uildRedPacketQueryReq\020\301\023\022\035\n\030CSGuildRedPa"
    "cketQueryRsp\020\302\023\022\034\n\027CSGuildRedPacketSendR"
    "eq\020\303\023\022\034\n\027CSGuildRedPacketSendRsp\020\304\023\022 \n\033C"
    "SGuildRedPacketGetAwardReq\020\305\023\022\032\n\025CSGuild"
    "RedPacketAward\020\306\023\022 \n\033CSGuildRedPacketGet"
    "AwardRsp\020\307\023\022\036\n\031CSGuildRedPacketRecordReq"
    "\020\310\023\022\032\n\025CSRedPacketRecordInfo\020\311\023\022\036\n\031CSGui"
    "ldRedPacketRecordRsp\020\312\023\022\"\n\035CSGuildRedPac"
    "ketFirstCheckReq\020\313\023\022\"\n\035CSGuildRedPacketF"
    "irstCheckRsp\020\314\023\022\037\n\032CSGuildRedPacketConfi"
    "gInfo\020\315\023\022\036\n\031CSGuildRedPacketConfigReq\020\316\023"
    "\022\036\n\031CSGuildRedPacketConfigRsp\020\317\023\022\016\n\tUnio"
    "nInfo\020\320\023\022\023\n\016CSUnionInfoReq\020\321\023\022\023\n\016CSUnion"
    "InfoRsp\020\322\023\022\024\n\017CSChangeNameReq\020\323\023\022\024\n\017CSCh"
    "angeNameRsp\020\324\023\022!\n\034CSNotifyItemExploreRew"
    "ardRsp\020\325\023\022\025\n\020CSExploreRestRsp\020\326\023\022\r\n\010carm"
    "sg07\020\327\023\022\r\n\010carmsg08\020\330\023\022\r\n\010carmsg09\020\331\023\022\r\n"
    "\010carmsg10\020\332\023\022\030\n\023CSRankRewardListReq\020\333\023\022\030"
    "\n\023CSRankRewardListRsp\020\334\023\022\027\n\022CSRecruitCom"
    "mitReq\020\335\023\022\027\n\022CSRecruitCommitRsp\020\336\023\022\026\n\021CS"
    "RecruitAwardReq\020\337\023\022\026\n\021CSRecruitAwardRsp\020"
    "\340\023\022\020\n\013RecruitInfo\020\341\023\022\025\n\020CSRecruitListReq"
    "\020\342\023\022\025\n\020CSRecruitListRsp\020\343\023\022\035\n\030CSExchange"
    "HighQualityReq\020\344\023\022\035\n\030CSExchangeHighQuali"
    "tyRsp\020\345\023\022\022\n\rCSTestOnlyReq\020\346\023\022\022\n\rCSTestOn"
    "lyRsp\020\347\023\022\r\n\010carmsg30\020\345\023\022\r\n\010carmsg31\020\346\023\022\036"
    "\n\031CSExchangeVocationInfoReq\020\347\023\022\021\n\014Vocati"
    "onInfo\020\350\023\022\036\n\031CSExchangeVocationInfoRsp\020\351"
    "\023\022\032\n\025CSExchangeVocationReq\020\352\023\022\032\n\025CSExcha"
    "ngeVocationRsp\020\353\023\022\014\n\007CSPoint\020\240\037\022\024\n\017CSBat"
    "tleMoveReq\020\241\037\022\024\n\017CSBattleMoveRsp\020\242\037\022\025\n\020M"
    "onsterMoveValue\020\243\037\022\025\n\020CSMonsterMoveRsp\020\244"
    "\037\022\026\n\021CSBattleCreateReq\020\245\037\022\026\n\021MonsterBatt"
    "leInfo\020\246\037\022\020\n\013MonsterInfo\020\247\037\022\026\n\021CSBattleC"
    "reateRsp\020\250\037\022\035\n\030CSBattleMonsterCreateRsp\020"
    "\251\037\022\030\n\023CSBattleUserJoinRsp\020\252\037\022\031\n\024CSBattle"
    "UserLeaveRsp\020\253\037\022\034\n\027CSBattleLoadCompleteR"
    "eq\020\254\037\022\034\n\027CSBattleLoadCompleteRsp\020\255\037\022\025\n\020C"
    "SBattleLeaveReq\020\256\037\022\025\n\020CSBattleLeaveRsp\020\257"
    "\037\022\027\n\022CSBattleTimeoutRsp\020\260\037\022\031\n\024CSBattlePl"
    "ayerDelRsp\020\261\037\022\035\n\030CSBattlePlayerRevivalRe"
    "q\020\262\037\022\035\n\030CSBattlePlayerRevivalRsp\020\263\037\022\026\n\021A"
    "ttackMonsterInfo\020\264\037\022\034\n\027CSAttackMonsterBa"
    "ckInfo\020\265\037\022\030\n\023CSMonsterAttackInfo\020\266\037\022\030\n\023C"
    "SMonsterEffectInfo\020\267\037\022\027\n\022CSMonsterAttack"
    "Rsp\020\270\037\022\027\n\022CSMonsterEffectRsp\020\271\037\022\034\n\027CSMon"
    "sterBuffEffectInfo\020\272\037\022\024\n\017CSBuffEffectRsp"
    "\020\273\037\022\024\n\017CSMonsterHitRsp\020\274\037\022\024\n\017CSSkillBegi"
    "nReq\020\275\037\022\024\n\017CSSkillBeginRsp\020\276\037\022\026\n\021CSPlaye"
    "rAttackReq\020\277\037\022\026\n\021CSPlayerAttackRsp\020\300\037\022\025\n"
    "\020AttackPlayerInfo\020\301\037\022\031\n\024CSPlayerHitPlaye"
    "rReq\020\302\037\022\031\n\024CSPlayerHitPlayerRsp\020\303\037\022\022\n\rCS"
    "PlayerHPRsp\020\304\037\022\022\n\rCSPlayerHPReq\020\305\037\022\026\n\021CS"
    "MonsterBloodRsp\020\306\037\022\024\n\017CSMonsterDieReq\020\307\037"
    "\022\024\n\017CSMonsterDieRsp\020\310\037\022\027\n\022CSPlayerDieSho"
    "wReq\020\311\037\022\027\n\022CSPlayerDieShowRsp\020\312\037\022\032\n\025CSPl"
    "ayerMayImproveReq\020\313\037\022\032\n\025CSPlayerMayImpro"
    "veRsp\020\314\037\022\027\n\022CSWBViewPlayersReq\020\315\037\022\030\n\023CSW"
    "BMonsterBloodRsp\020\316\037\022\026\n\021CSWBPlayerFailRsp"
    "\020\317\037\022\034\n\027CSWBBtlPlayerRevivalReq\020\320\037\022\027\n\022CSW"
    "BHurtStatistics\020\321\037\022\026\n\021CSWBRTHurtRankReq\020"
    "\322\037\022\026\n\021CSWBRTHurtRankRsp\020\323\037\022\022\n\rCSWBReward"
    "Req\020\324\037\022\022\n\rCSWBRewardRsp\020\325\037\022\034\n\027CSBattleUs"
    "erAddBloodRsp\020\326\037\022\027\n\022CSWBBattleLeaveReq\020\327"
    "\037\022\030\n\023CSWBBattleFinishRsp\020\330\037\022\026\n\021CSCBHurtN"
    "otifyRsp\020\331\037\022\027\n\022CSCBFinshBattleRsp\020\332\037\022\022\n\r"
    "CSCBDoubleReq\020\333\037\022\022\n\rCSCBDoubleRsp\020\334\037\022\030\n\023"
    "CSBBMonsterBloodRsp\020\335\037\022\027\n\022CSBBBattleLeav"
    "eReq\020\336\037\022\025\n\020CSBabelRewardRsp\020\337\037\022\023\n\016CSBabe"
    "lFailRsp\020\340\037\022\023\n\016CSCityBloodRsp\020\341\037\022\020\n\013CSRa"
    "ngeInfo\020\360.\022\024\n\017CSMonsterInfo_t\020\361.\022\023\n\016CSMa"
    "pMonster_t\020\362.\022\030\n\023CSMapMonsterGroup_t\020\363.\022"
    "\023\n\016CSMapContent_t\020\364.\022\027\n\022CSMapContentList"
    "_t\020\365.\022\025\n\020CSMonsterValue_t\020\366.\022\027\n\022CSBattle"
    "PrepareReq\020\367.\022\027\n\022CSBattlePrepareRsp\020\370.\022\030"
    "\n\023InterAttributesInfo\020\300>\022\027\n\022InterUserSki"
    "llInfo\020\301>\022\022\n\rInterItemInfo\020\302>\022\035\n\030inter_f"
    "airy_basic_info_t\020\303>\022\035\n\030inter_fairy_trai"
    "n_info_t\020\304>\022\023\n\016InterFairyInfo\020\305>\022\016\n\tInte"
    "rSync\020\306>\022\r\n\010InterOut\020\307>\022\020\n\013InterDbSync\020\310"
    ">", 15881);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "head.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_head_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_head_2eproto {
  StaticDescriptorInitializer_head_2eproto() {
    protobuf_AddDesc_head_2eproto();
  }
} static_descriptor_initializer_head_2eproto_;

const ::google::protobuf::EnumDescriptor* CSMsgName_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CSMsgName_descriptor_;
}
bool CSMsgName_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 2000:
    case 2001:
    case 2002:
    case 2003:
    case 2004:
    case 2005:
    case 2006:
    case 2007:
    case 2008:
    case 2009:
    case 2010:
    case 2011:
    case 2012:
    case 2013:
    case 2014:
    case 2015:
    case 2016:
    case 2017:
    case 2018:
    case 2019:
    case 2020:
    case 2021:
    case 2022:
    case 2023:
    case 2024:
    case 2025:
    case 2026:
    case 2027:
    case 2028:
    case 2029:
    case 2030:
    case 2031:
    case 2032:
    case 2033:
    case 2034:
    case 2035:
    case 2036:
    case 2037:
    case 2038:
    case 2039:
    case 2040:
    case 2041:
    case 2042:
    case 2043:
    case 2044:
    case 2045:
    case 2046:
    case 2047:
    case 2048:
    case 2049:
    case 2050:
    case 2051:
    case 2052:
    case 2053:
    case 2054:
    case 2055:
    case 2056:
    case 2057:
    case 2058:
    case 2059:
    case 2060:
    case 2061:
    case 2062:
    case 2063:
    case 2064:
    case 2065:
    case 2066:
    case 2067:
    case 2068:
    case 2069:
    case 2070:
    case 2071:
    case 2072:
    case 2073:
    case 2074:
    case 2075:
    case 2076:
    case 2077:
    case 2078:
    case 2079:
    case 2080:
    case 2081:
    case 2082:
    case 2083:
    case 2084:
    case 2085:
    case 2086:
    case 2087:
    case 2088:
    case 2089:
    case 2090:
    case 2091:
    case 2092:
    case 2093:
    case 2094:
    case 2095:
    case 2096:
    case 2097:
    case 2098:
    case 2099:
    case 2100:
    case 2101:
    case 2102:
    case 2103:
    case 2104:
    case 2105:
    case 2106:
    case 2107:
    case 2108:
    case 2109:
    case 2110:
    case 2111:
    case 2112:
    case 2113:
    case 2114:
    case 2115:
    case 2116:
    case 2117:
    case 2118:
    case 2119:
    case 2120:
    case 2121:
    case 2122:
    case 2123:
    case 2124:
    case 2125:
    case 2126:
    case 2127:
    case 2128:
    case 2129:
    case 2130:
    case 2131:
    case 2132:
    case 2133:
    case 2134:
    case 2135:
    case 2136:
    case 2137:
    case 2138:
    case 2139:
    case 2140:
    case 2141:
    case 2142:
    case 2143:
    case 2144:
    case 2145:
    case 2146:
    case 2147:
    case 2148:
    case 2149:
    case 2150:
    case 2151:
    case 2152:
    case 2153:
    case 2154:
    case 2155:
    case 2156:
    case 2157:
    case 2158:
    case 2159:
    case 2160:
    case 2161:
    case 2162:
    case 2163:
    case 2164:
    case 2165:
    case 2166:
    case 2167:
    case 2168:
    case 2169:
    case 2170:
    case 2171:
    case 2172:
    case 2173:
    case 2174:
    case 2175:
    case 2176:
    case 2177:
    case 2178:
    case 2179:
    case 2180:
    case 2181:
    case 2182:
    case 2183:
    case 2184:
    case 2185:
    case 2186:
    case 2187:
    case 2188:
    case 2189:
    case 2190:
    case 2191:
    case 2192:
    case 2193:
    case 2194:
    case 2195:
    case 2196:
    case 2197:
    case 2198:
    case 2199:
    case 2200:
    case 2201:
    case 2202:
    case 2203:
    case 2204:
    case 2205:
    case 2206:
    case 2207:
    case 2208:
    case 2209:
    case 2210:
    case 2211:
    case 2212:
    case 2213:
    case 2214:
    case 2215:
    case 2216:
    case 2217:
    case 2218:
    case 2219:
    case 2220:
    case 2221:
    case 2222:
    case 2223:
    case 2224:
    case 2225:
    case 2226:
    case 2227:
    case 2228:
    case 2229:
    case 2230:
    case 2231:
    case 2232:
    case 2233:
    case 2234:
    case 2235:
    case 2236:
    case 2237:
    case 2238:
    case 2239:
    case 2240:
    case 2241:
    case 2242:
    case 2243:
    case 2244:
    case 2245:
    case 2246:
    case 2247:
    case 2248:
    case 2249:
    case 2250:
    case 2251:
    case 2252:
    case 2253:
    case 2254:
    case 2255:
    case 2256:
    case 2257:
    case 2258:
    case 2259:
    case 2260:
    case 2261:
    case 2262:
    case 2263:
    case 2264:
    case 2265:
    case 2266:
    case 2267:
    case 2268:
    case 2269:
    case 2270:
    case 2271:
    case 2272:
    case 2273:
    case 2274:
    case 2275:
    case 2276:
    case 2277:
    case 2278:
    case 2279:
    case 2280:
    case 2281:
    case 2282:
    case 2283:
    case 2284:
    case 2285:
    case 2286:
    case 2287:
    case 2288:
    case 2289:
    case 2290:
    case 2291:
    case 2292:
    case 2293:
    case 2294:
    case 2295:
    case 2296:
    case 2297:
    case 2298:
    case 2299:
    case 2300:
    case 2301:
    case 2302:
    case 2303:
    case 2304:
    case 2305:
    case 2306:
    case 2307:
    case 2308:
    case 2309:
    case 2310:
    case 2311:
    case 2312:
    case 2313:
    case 2314:
    case 2315:
    case 2316:
    case 2317:
    case 2318:
    case 2319:
    case 2320:
    case 2321:
    case 2322:
    case 2323:
    case 2324:
    case 2325:
    case 2326:
    case 2327:
    case 2328:
    case 2329:
    case 2330:
    case 2331:
    case 2332:
    case 2333:
    case 2334:
    case 2335:
    case 2336:
    case 2337:
    case 2338:
    case 2339:
    case 2340:
    case 2341:
    case 2342:
    case 2343:
    case 2344:
    case 2345:
    case 2346:
    case 2347:
    case 2348:
    case 2349:
    case 2350:
    case 2351:
    case 2352:
    case 2353:
    case 2354:
    case 2355:
    case 2356:
    case 2357:
    case 2358:
    case 2359:
    case 2360:
    case 2361:
    case 2362:
    case 2363:
    case 2364:
    case 2365:
    case 2366:
    case 2367:
    case 2368:
    case 2369:
    case 2370:
    case 2371:
    case 2372:
    case 2373:
    case 2374:
    case 2375:
    case 2376:
    case 2377:
    case 2378:
    case 2379:
    case 2380:
    case 2381:
    case 2382:
    case 2383:
    case 2384:
    case 2385:
    case 2386:
    case 2387:
    case 2388:
    case 2389:
    case 2390:
    case 2391:
    case 2392:
    case 2393:
    case 2394:
    case 2395:
    case 2396:
    case 2397:
    case 2398:
    case 2399:
    case 2400:
    case 2401:
    case 2402:
    case 2403:
    case 2404:
    case 2405:
    case 2406:
    case 2407:
    case 2408:
    case 2409:
    case 2410:
    case 2411:
    case 2412:
    case 2413:
    case 2414:
    case 2415:
    case 2416:
    case 2417:
    case 2418:
    case 2419:
    case 2420:
    case 2421:
    case 2422:
    case 2423:
    case 2424:
    case 2425:
    case 2426:
    case 2427:
    case 2428:
    case 2429:
    case 2430:
    case 2431:
    case 2432:
    case 2433:
    case 2434:
    case 2435:
    case 2436:
    case 2437:
    case 2438:
    case 2439:
    case 2440:
    case 2441:
    case 2442:
    case 2443:
    case 2444:
    case 2445:
    case 2446:
    case 2447:
    case 2448:
    case 2449:
    case 2450:
    case 2451:
    case 2452:
    case 2453:
    case 2454:
    case 2455:
    case 2456:
    case 2457:
    case 2458:
    case 2459:
    case 2460:
    case 2461:
    case 2462:
    case 2463:
    case 2464:
    case 2465:
    case 2466:
    case 2467:
    case 2468:
    case 2469:
    case 2470:
    case 2471:
    case 2472:
    case 2473:
    case 2474:
    case 2475:
    case 2476:
    case 2477:
    case 2478:
    case 2479:
    case 2480:
    case 2481:
    case 2482:
    case 2483:
    case 2484:
    case 2485:
    case 2486:
    case 2487:
    case 2488:
    case 2489:
    case 2490:
    case 2491:
    case 2492:
    case 2493:
    case 2494:
    case 2495:
    case 2496:
    case 2497:
    case 2498:
    case 2499:
    case 2500:
    case 2501:
    case 2502:
    case 2503:
    case 2504:
    case 2505:
    case 2506:
    case 2507:
    case 2508:
    case 2509:
    case 2510:
    case 2511:
    case 2512:
    case 2513:
    case 2514:
    case 2515:
    case 2516:
    case 2517:
    case 2518:
    case 2519:
    case 2520:
    case 2521:
    case 2522:
    case 2523:
    case 2524:
    case 2525:
    case 2526:
    case 2527:
    case 2528:
    case 2529:
    case 2530:
    case 2531:
    case 2532:
    case 2533:
    case 2534:
    case 2535:
    case 2536:
    case 2537:
    case 2538:
    case 2539:
    case 4000:
    case 4001:
    case 4002:
    case 4003:
    case 4004:
    case 4005:
    case 4006:
    case 4007:
    case 4008:
    case 4009:
    case 4010:
    case 4011:
    case 4012:
    case 4013:
    case 4014:
    case 4015:
    case 4016:
    case 4017:
    case 4018:
    case 4019:
    case 4020:
    case 4021:
    case 4022:
    case 4023:
    case 4024:
    case 4025:
    case 4026:
    case 4027:
    case 4028:
    case 4029:
    case 4030:
    case 4031:
    case 4032:
    case 4033:
    case 4034:
    case 4035:
    case 4036:
    case 4037:
    case 4038:
    case 4039:
    case 4040:
    case 4041:
    case 4042:
    case 4043:
    case 4044:
    case 4045:
    case 4046:
    case 4047:
    case 4048:
    case 4049:
    case 4050:
    case 4051:
    case 4052:
    case 4053:
    case 4054:
    case 4055:
    case 4056:
    case 4057:
    case 4058:
    case 4059:
    case 4060:
    case 4061:
    case 4062:
    case 4063:
    case 4064:
    case 4065:
    case 6000:
    case 6001:
    case 6002:
    case 6003:
    case 6004:
    case 6005:
    case 6006:
    case 6007:
    case 6008:
    case 8000:
    case 8001:
    case 8002:
    case 8003:
    case 8004:
    case 8005:
    case 8006:
    case 8007:
    case 8008:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace head_msg

// @@protoc_insertion_point(global_scope)
