Explore={}
Explore[1000]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_1',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1001]={UI_ID='0',LookFace='ui_explore_map_2',UI_Name='EXPLORE_MAP_2',Event='EXPLORE_EVENT_2',Option1_Text='EXPLORE_EVENT_2_ANSWER_1',Option2_Text='EXPLORE_EVENT_2_ANSWER_2',}
Explore[1002]={UI_ID='0',LookFace='ui_explore_map_3',UI_Name='EXPLORE_MAP_3',Event='EXPLORE_EVENT_3',Option1_Text='EXPLORE_EVENT_3_ANSWER_1',Option2_Text='EXPLORE_EVENT_3_ANSWER_2',}
Explore[1003]={UI_ID='1/2003',LookFace='ui_explore_map_4',UI_Name='EXPLORE_MAP_4',Event='EXPLORE_EVENT_4',Option1_Text='EXPLORE_EVENT_4_ANSWER_1',Option2_Text='EXPLORE_EVENT_4_ANSWER_2',}
Explore[1004]={UI_ID='0',LookFace='ui_explore_map_5',UI_Name='EXPLORE_MAP_5',Event='EXPLORE_EVENT_5',Option1_Text='EXPLORE_EVENT_5_ANSWER_1',Option2_Text='EXPLORE_EVENT_5_ANSWER_2',}
Explore[1005]={UI_ID='0',LookFace='ui_explore_map_6',UI_Name='EXPLORE_MAP_6',Event='EXPLORE_EVENT_6',Option1_Text='EXPLORE_EVENT_6_ANSWER_1',Option2_Text='EXPLORE_EVENT_6_ANSWER_2',}
Explore[1006]={UI_ID='0',LookFace='ui_explore_map_7',UI_Name='EXPLORE_MAP_7',Event='EXPLORE_EVENT_7',Option1_Text='EXPLORE_EVENT_7_ANSWER_1',Option2_Text='EXPLORE_EVENT_7_ANSWER_2',}
Explore[1007]={UI_ID='0',LookFace='ui_explore_map_8',UI_Name='EXPLORE_MAP_8',Event='EXPLORE_EVENT_8',Option1_Text='EXPLORE_EVENT_8_ANSWER_1',Option2_Text='EXPLORE_EVENT_8_ANSWER_2',}
Explore[1008]={UI_ID='0',LookFace='ui_explore_map_9',UI_Name='EXPLORE_MAP_9',Event='EXPLORE_EVENT_9',Option1_Text='EXPLORE_EVENT_9_ANSWER_1',Option2_Text='EXPLORE_EVENT_9_ANSWER_2',}
Explore[1009]={UI_ID='0',LookFace='ui_explore_map_10',UI_Name='EXPLORE_MAP_10',Event='EXPLORE_EVENT_10',Option1_Text='EXPLORE_EVENT_10_ANSWER_1',Option2_Text='EXPLORE_EVENT_10_ANSWER_2',}
Explore[1010]={UI_ID='0',LookFace='ui_explore_map_11',UI_Name='EXPLORE_MAP_11',Event='EXPLORE_EVENT_11',Option1_Text='EXPLORE_EVENT_11_ANSWER_1',Option2_Text='EXPLORE_EVENT_11_ANSWER_2',}
Explore[1011]={UI_ID='1/2021',LookFace='ui_explore_map_12',UI_Name='EXPLORE_MAP_12',Event='EXPLORE_EVENT_12',Option1_Text='EXPLORE_EVENT_12_ANSWER_1',Option2_Text='EXPLORE_EVENT_12_ANSWER_2',}
Explore[1012]={UI_ID='0',LookFace='ui_explore_map_13',UI_Name='EXPLORE_MAP_13',Event='EXPLORE_EVENT_13',Option1_Text='EXPLORE_EVENT_13_ANSWER_1',Option2_Text='EXPLORE_EVENT_13_ANSWER_2',}
Explore[1013]={UI_ID='0',LookFace='ui_explore_map_14',UI_Name='EXPLORE_MAP_14',Event='EXPLORE_EVENT_14',Option1_Text='EXPLORE_EVENT_14_ANSWER_1',Option2_Text='EXPLORE_EVENT_14_ANSWER_2',}
Explore[1014]={UI_ID='2/2015',LookFace='ui_explore_map_15',UI_Name='EXPLORE_MAP_15',Event='EXPLORE_EVENT_15',Option1_Text='EXPLORE_EVENT_15_ANSWER_1',Option2_Text='EXPLORE_EVENT_15_ANSWER_2',}
Explore[1015]={UI_ID='0',LookFace='ui_explore_map_16',UI_Name='EXPLORE_MAP_16',Event='EXPLORE_EVENT_16',Option1_Text='EXPLORE_EVENT_16_ANSWER_1',Option2_Text='EXPLORE_EVENT_16_ANSWER_2',}
Explore[1016]={UI_ID='0',LookFace='ui_explore_map_17',UI_Name='EXPLORE_MAP_17',Event='EXPLORE_EVENT_17',Option1_Text='EXPLORE_EVENT_17_ANSWER_1',Option2_Text='EXPLORE_EVENT_17_ANSWER_2',}
Explore[1017]={UI_ID='2/2018',LookFace='ui_explore_map_18',UI_Name='EXPLORE_MAP_18',Event='EXPLORE_EVENT_18',Option1_Text='EXPLORE_EVENT_18_ANSWER_1',Option2_Text='EXPLORE_EVENT_18_ANSWER_2',}
Explore[1018]={UI_ID='0',LookFace='ui_explore_map_19',UI_Name='EXPLORE_MAP_19',Event='EXPLORE_EVENT_19',Option1_Text='EXPLORE_EVENT_19_ANSWER_1',Option2_Text='EXPLORE_EVENT_19_ANSWER_2',}
Explore[1019]={UI_ID='0',LookFace='ui_explore_map_20',UI_Name='EXPLORE_MAP_20',Event='EXPLORE_EVENT_20',Option1_Text='EXPLORE_EVENT_20_ANSWER_1',Option2_Text='EXPLORE_EVENT_20_ANSWER_2',}
Explore[1020]={UI_ID='1/2024',LookFace='ui_explore_map_21',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_21',Option1_Text='EXPLORE_EVENT_21_ANSWER_1',Option2_Text='EXPLORE_EVENT_21_ANSWER_2',}
Explore[1021]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1022]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1023]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1024]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1025]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1026]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1027]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1028]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1029]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1030]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1031]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1032]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1033]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1034]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1035]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1036]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1037]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1038]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1039]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1040]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
Explore[1041]={UI_ID='0',LookFace='ui_explore_map_1',UI_Name='EXPLORE_MAP_21',Event='EXPLORE_EVENT_1',Option1_Text='EXPLORE_EVENT_1_ANSWER_1',Option2_Text='EXPLORE_EVENT_1_ANSWER_2',}
