fairysunlock={}
fairysunlock[1]={Unlock_level='1',}
fairysunlock[2]={Unlock_level='4',}
fairysunlock[20]={Unlock_level='13',}
fairysunlock[21]={Unlock_level='20',}
fairysunlock[50]={Unlock_level='25',}
fairysunlock[51]={Unlock_level='30',}
fairysunlock[52]={Unlock_level='35',}
fairysunlock[53]={Unlock_level='40',}
fairysunlock[54]={Unlock_level='50',}
fairysunlock[55]={Unlock_level='60',}
