GM={}
GM[1]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[2]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[3]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[4]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[5]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[13]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[14]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[15]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[16]={user_center='0',radiers='1',game_center='1',enter_web='1',hot_issues='0',}
GM[17]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[18]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[19]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[20]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[21]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[22]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[23]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[24]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[25]={user_center='1',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[26]={user_center='1',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[27]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[28]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[29]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[30]={user_center='0',radiers='1',game_center='1',enter_web='1',hot_issues='0',}
GM[31]={user_center='0',radiers='1',game_center='1',enter_web='1',hot_issues='0',}
GM[32]={user_center='0',radiers='1',game_center='1',enter_web='1',hot_issues='0',}
GM[33]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[34]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[35]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[36]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[37]={user_center='0',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[38]={user_center='1',radiers='0',game_center='0',enter_web='0',hot_issues='1',}
GM[61]={user_center='1',radiers='0',game_center='0',enter_web='0',hot_issues='0',}
